server:
  port: 8080

spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
#  flyway:
#    enabled: true
#    locations: classpath:db/migration

#  security:
#    user:
#      name: admin
#      password: admin
#      roles: USER

logging:
  level:
    org:
      flywaydb:
        core: DEBUG
      springframework:
        data: DEBUG